# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        # Set always-auth in npmrc
        # always-auth: # optional, default is false
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
        node-version: 11.x # optional, default is 10.x
        # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN
        # registry-url: # optional
        # Optional scope for authenticating against scoped registries
        # scope: # optional
    - name: Yarn CLI
      uses: CultureHQ/actions-yarn@v1.0.1
    - name: Install Dependencies
      run: |
        yarn
        yarn run build
    
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.0.1
      with:
        # GitHub repository where assets will be deployed (default current)
        # repo: # optional
        # Git branch where assets will be deployed
        # target_branch: # optional, default is gh-pages
        # Create incremental commit instead of doing push force
        # keep_history: # optional, default is false
        # Allow an empty commit to be created
        # allow_empty_commit: # optional, default is true
        # Build directory to deploy
        build_dir: dist
        # The committer name and email address
        committer: slj196 # optional
        # The author name and email address
        author: slj196 # optional
        # Commit message
        # commit_message: # optional
        # Write the given domain name to the CNAME file
        # fqdn: # optional
